/*
 * OptimizationTab.h
 *
 *  Created on: Oct 30, 2009
 *      Author: alexgc
 */

#ifndef OPTIMIZATIONTAB_H_
#define OPTIMIZATIONTAB_H_

#include "RSTTab.h"
#include "../Tools/Optimizer.h"

class OptimizationTab : public RSTTab
{
public:
	OptimizationTab(){};
    OptimizationTab(wxWindow * parent, wxWindowID id = -1,
             const wxPoint & pos = wxDefaultPosition,
             const wxSize & size = wxDefaultSize,
             long style = wxTAB_TRAVERSAL);
	virtual ~OptimizationTab(){}

	wxSizer* sizerFull;

	// Generic button handler - will swtich between button IDs
    void OnButton(wxCommandEvent &evt);

    // Optimizer object - stores paths and executes optimization
    Optimizer optimizer;

    /**
     * Execute optimization takes an already-created path and
     * optimizes it.
     * NOTE: the path must have already been generated by the
     * planner for this to work
     */
    void executeOptimize();

    /**
     * Copy in the path to the overall system timeline
     * @param path of a robot
     * Writes the path into the main timeslices vector in RSTFrame
     */
    void SetTimeline(const Path_t& path);

    // these functions swap the paths stored in RRT
    void setOriginalPath();
    void setOptimizedPath();

	void OnSlider(wxCommandEvent &evt);
	void RSTStateChange();

	DECLARE_DYNAMIC_CLASS(OptimizationTab)
	DECLARE_EVENT_TABLE()
};

#endif /* OPTIMIZATIONTAB_H_ */
